# Generated by Django 2.0.2 on 2019-11-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_music_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='track_file',
            field=models.FileField(default='', upload_to='media/tracks'),
            preserve_default=False,
        ),
    ]
