# Generated by Django 2.0.2 on 2019-11-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track_file',
            field=models.FileField(blank=True, upload_to='media/tracks'),
        ),
        migrations.AlterField(
            model_name='music',
            name='track_link',
            field=models.URLField(blank=True),
        ),
    ]
