# Generated by Django 2.0.2 on 2019-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191018_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='link',
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Debian Certification', max_length=255),
            preserve_default=False,
        ),
    ]
