# Generated by Django 2.0.2 on 2019-11-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('att', models.FileField(blank=True, upload_to='media/attatchments')),
            ],
        ),
    ]
