# Generated by Django 2.0.2 on 2019-10-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_summary',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
