# Generated by Django 2.0.2 on 2019-10-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_summary',
        ),
    ]
